version: '3'

services:
  carros-py:
    build: .
    ports:
      - 8081:8081
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: "27017"
    links:
      - mongo
    networks:
      - carros-network

  mongo:
    image: mongo
    expose:
      - "27017"
      - "28017"
    volumes:
      - /home/leomontero/mongo_bkp:/data/db
    networks:
      - carros-network

networks: 
    carros-network:
      driver: bridge